# Copyright 2011, 2012 Wenjun Deng <wdeng@wdeng.info>
#
# This file is part of ALCON
#
# ALCON is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ALCON is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ALCON.  If not, see <http://www.gnu.org/licenses/>.


# Makefile to compile and run ALCON
# use with GNU make or a compatible alternative

# adjust the following parameters according to your system environment before
#   compiling and running ALCON

# MPI Fortran 90 compiler
MPIF90 := mpif90

# compiling options
FFLAGS := -O2

# MPI executor
MPIEXEC := mpiexec

# number of MPI processes to run ALCON
NPE := 2


# module object files
MODOBJ := alcon_input.o alcon_eqdata.o alcon_solver.o alcon_output.o \
 cspline_petsc.o

.PHONY : build run clean cleanoutput

build : alcon

# SLEPc variables
-include $(SLEPC_DIR)/conf/slepc_variables

# first layer dependency files .d1
-include $(MODOBJ:.o=.d1)

# use GNU tools to build module dependency files .d1
# each .d1 file gives rules to generate corresponding .d2 file
# .d2 files are generated by Fortran compiler with -MM option
# corresponding .mod files are generated when compiler generates .d2 files
$(MODOBJ:.o=.d1) : %.d1 : %.F90
	@echo 'making $@...'
	@echo '-include $(@:.d1=.d2)' > $@
	@exec echo -n '$(@:.d1=.d2) : $< ' >> $@
	@exec sed -n 's/^[ \t]*use \([^ \t,]*\).*$$/\1.mod/p' $< | sort | uniq | paste -s --delimiters=" " >> $@
	@exec echo -e '\t$$(MPIF90) $(FFLAGS) -MM $$< $$(FCPPFLAGS) > $$@' >> $@
	@echo 'finished making $@'

# compile main program and link all modules
alcon : alcon.F90 $(MODOBJ)
	$(MPIF90) $(FFLAGS) -o $@ $^ $(FCPPFLAGS) $(SLEPC_LIB)

# compile testcsp
testcsp : testcsp.F90 cspline_petsc.o
	$(MPIF90) $(FFLAGS) -o $@ $^ $(FCPPFLAGS) $(SLEPC_LIB)

# compile modules
$(MODOBJ) : %.o : %.F90 %.d2
	$(MPIF90) $(FFLAGS) -c -o $@ $< $(FCPPFLAGS)

run : alcon cleanoutput
	mkdir -p output
	$(MPIEXEC) -n $(NPE) ./$< 2>&1 | tee $<.log

runtestcsp : testcsp
	$(MPIEXEC) -n $(NPE) ./$< 2>&1 | tee $<.log

clean :
	rm -f alcon testcsp *.o *.mod *.d1 *.d2 *.log

cleanoutput :
	rm -f output/*

